# Generated by Django 4.2.5 on 2023-09-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='전화번호')),
                ('content', models.TextField(default='비어있습니다 내용을 작성해주세요', verbose_name='내용')),
                ('student_number', models.IntegerField(verbose_name='학번')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
            ],
        ),
    ]
