# Generated by Django 4.2.5 on 2023-09-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demos',
            new_name='Post',
        ),
    ]
